### ISSUE TITLE
Image reponsive and reduce font in mobile view

### ISSUE THREAD

**Issue by titipata** [pavanramkumar/pavanramkumar.github.io#2]
Hey @bluenex, so we want to make image responsive and also reduce font size a bit in mobile view.  It would also be great if we can add `zoom.js` into Desktop version so people can zoom the image.

**Comment by titipata** [comment]
If @pavanramkumar, this issue can be close.

**Comment by pavanramkumar** [comment]
thanks @titipata @bluenex!
